# Generated by Django 5.2.3 on 2025-06-30 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('branch', models.CharField(choices=[('Literary', 'Literary'), ('Scientific', 'Scientific'), ('Ninth', 'Ninth')], max_length=10)),
                ('birth_date', models.DateField()),
                ('student_number', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=50)),
                ('registration_date', models.DateField(default=datetime.datetime.now)),
                ('father_name', models.CharField(max_length=100)),
                ('father_job', models.CharField(blank=True, max_length=100, null=True)),
                ('father_phone', models.CharField(max_length=20)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_job', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('home_phone', models.CharField(max_length=20)),
                ('previous_school', models.CharField(blank=True, max_length=100, null=True)),
                ('elementary_school', models.CharField(blank=True, max_length=100, null=True)),
                ('how_knew_us', models.CharField(blank=True, choices=[('friend', 'Friend'), ('social', 'Social'), ('ad', 'Ad'), ('other', 'Other')], max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
