# Generated by Django 5.2.3 on 2025-08-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('أدبي', 'الأدبي'), ('علمي', 'العلمي'), ('تاسع', 'الصف التاسع')], max_length=10),
        ),
    ]
