# Generated by Django 5.2.3 on 2025-08-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='base_required_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
