# Generated by Django 5.2.3 on 2025-08-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_base_required_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='base_required_amount',
        ),
    ]
