# Generated by Django 5.2.3 on 2025-08-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_base_required_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='disease',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tase3',
            field=models.IntegerField(default=0),
        ),
    ]
