# Generated by Django 5.2.3 on 2025-08-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_disease_student_tase3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='disease',
            field=models.TextField(blank=True, default='none'),
        ),
        migrations.AlterField(
            model_name='student',
            name='elementary_school',
            field=models.CharField(blank=True, default='sback', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_job',
            field=models.CharField(blank=True, default='ds', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_job',
            field=models.CharField(blank=True, default='mjob', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, default='mname', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, default='none'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='previous_school',
            field=models.CharField(blank=True, default='psc', max_length=100),
            preserve_default=False,
        ),
    ]
