# Generated by Django 5.2.3 on 2025-08-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='elementary_school',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
