# Generated by Django 5.2.3 on 2025-08-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_elementary_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='how_knew_us',
            field=models.CharField(blank=True, choices=[('اصدقاء', 'Friend'), ('سوشيال ميديا', 'Social'), ('مقابلة تلفزيونية', 'Ad'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
