# Generated by Django 5.2.3 on 2025-08-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='how_knew_us',
            field=models.CharField(blank=True, choices=[('friend', 'صديق'), ('social', 'وسائل التواصل الاجتماعي'), ('ad', 'إعلان'), ('ads', 'إعلانات طرقية'), ('other', 'أخرى')], max_length=100, null=True),
        ),
    ]
