# Generated by Django 5.2.3 on 2025-07-01 06:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='الاسم الكامل')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='رقم الهاتف')),
                ('id_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='رقم الهوية')),
                ('subject', models.CharField(choices=[('math', 'الرياضيات'), ('physics', 'الفيزياء'), ('chemistry', 'الكيمياء'), ('biology', 'علوم'), ('arabic', 'اللغة العربية'), ('english', 'اللغة الإنجليزية'), ('french', 'اللغة الفرنسية'), ('history', 'التاريخ'), ('geography', 'الجغرافيا'), ('philosophy', 'الفلسفة'), ('religion', 'التربية الإسلامية')], max_length=20, verbose_name='المادة')),
                ('branches', models.CharField(help_text='الفروع التي يدرسها المدرس (يمكن اختيار أكثر من فرع)', max_length=100, verbose_name='الفروع')),
                ('contract_type', models.CharField(choices=[('full-time', 'بكلوريا'), ('part-time', 'تاسع'), ('hourly', 'مشترك')], max_length=20, verbose_name='نوع العقد')),
                ('hire_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ التعيين')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مدرس',
                'verbose_name_plural': 'المدرسون',
                'ordering': ['-created_at'],
            },
        ),
    ]
