# Generated by Django 5.2.3 on 2025-08-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('admin', 'إداري'), ('accountant', 'محاسب'), ('mentor', 'موجه'), ('manager', 'مدير'), ('marketing', 'تسويق'), ('reception', 'استقبال')], max_length=20),
        ),
    ]
