# Generated by Django 5.2.3 on 2025-08-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0003_alter_employee_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
