# Generated by Django 5.2.3 on 2025-08-23 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0004_remove_teacher_contract_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_type', models.CharField(choices=[('يومية', 'يومية'), ('طارئة', 'طارئة'), ('مرضية', 'مرضية')], max_length=20, verbose_name='نوع الإجازة')),
                ('reason', models.TextField(verbose_name='سبب الإجازة')),
                ('start_date', models.DateField(verbose_name='تاريخ بدء الإجازة')),
                ('end_date', models.DateField(verbose_name='تاريخ انتهاء الإجازة')),
                ('submission_date', models.DateField(auto_now_add=True, verbose_name='تاريخ تقديم الطلب')),
                ('is_replacement_secured', models.BooleanField(default=False, verbose_name='تم تأمين البديل')),
                ('manager_opinion', models.TextField(blank=True, null=True, verbose_name='رأي المدير')),
                ('general_manager_opinion', models.TextField(blank=True, null=True, verbose_name='رأي المدير العام')),
                ('status', models.CharField(choices=[('معلقة', 'معلقة'), ('موافق', 'موافق'), ('غير موافق', 'غير موافق')], default='معلقة', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='employ.employee')),
            ],
            options={
                'verbose_name': 'إجازة',
                'verbose_name_plural': 'الإجازات',
                'ordering': ['-created_at'],
            },
        ),
    ]
