# Generated by Django 5.2.3 on 2025-08-10 17:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0002_alter_student_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='العلامة')),
                ('exam_type', models.CharField(choices=[('monthly', 'شهري'), ('midterm', 'نصفي'), ('final', 'نهائي'), ('activity', 'نشاط')], max_length=50, verbose_name='نوع الامتحان')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'علامة',
                'verbose_name_plural': 'العلامات',
                'ordering': ['-date', 'student__full_name'],
            },
        ),
    ]
