# Generated by Django 5.2.3 on 2025-08-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('grade', '0002_grade_classroom'),
        ('students', '0002_alter_student_branch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'exam_type')},
        ),
    ]
