# Generated by Django 5.2.3 on 2025-08-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0003_alter_grade_unique_together'),
    ]

    operations = [
    ]
