# Generated by Django 5.2.3 on 2025-08-21 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0004_clean_duplicate_grades'),
        ('students', '0014_alter_student_gender_alter_student_how_knew_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student'),
        ),
    ]
