# Generated by Django 5.2.3 on 2025-08-23 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0005_alter_grade_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='exam_type',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('midterm', 'نصفي')], max_length=50, verbose_name='نوع الامتحان'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='العلامة'),
        ),
    ]
