# Generated by Django 5.2.3 on 2025-08-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0006_alter_grade_exam_type_alter_grade_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='exam_type',
            field=models.CharField(choices=[('monthly', 'شهري'), ('midterm', 'نصفي'), ('final', 'نهائي'), ('activity', 'نشاط')], max_length=50, verbose_name='نوع الامتحان'),
        ),
    ]
