# Generated by Django 5.2.3 on 2025-08-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='الشعبة 1', max_length=50, verbose_name='اسم الشعبة')),
                ('branches', models.CharField(choices=[('أدبي', 'الأدبي'), ('علمي', 'العلمي'), ('تاسع', 'الصف التاسع')], default='علمي', max_length=100, verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'شعبة',
                'verbose_name_plural': 'شعب',
            },
        ),
    ]
