# Generated by Django 5.2.3 on 2025-08-10 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_classroomenrollment'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomenrollment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classroom.classroom'),
        ),
        migrations.AlterField(
            model_name='classroomenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_enrollments', to='students.student'),
        ),
    ]
