# Generated by Django 5.2.3 on 2025-08-10 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_classroomenrollment_classroom_and_more'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom', verbose_name='الشعبة')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'مادة الشعبة',
                'verbose_name_plural': 'مواد الشعب',
                'unique_together': {('classroom', 'subject')},
            },
        ),
    ]
