# Generated by Django 5.2.3 on 2025-08-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_classroomsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_type',
            field=models.CharField(choices=[('study', 'شعبة دراسية'), ('course', 'دورة')], default='study', max_length=10, verbose_name='نوع الشعبة'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='branches',
            field=models.CharField(blank=True, choices=[('أدبي', 'الأدبي'), ('علمي', 'العلمي'), ('تاسع', 'الصف التاسع')], max_length=100, null=True, verbose_name='الفرع'),
        ),
    ]
