# Generated by Django 5.2.3 on 2025-08-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_full',
        ),
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='مسدد بالكامل'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('course', 'دورة'), ('installment', 'قسط')], default='course', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='required_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
