# Generated by Django 5.2.3 on 2025-08-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_transaction_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('course', 'دورة'), ('installment', 'قسط'), ('settlement', 'تسديد حساب')], default='course', max_length=20),
        ),
    ]
