# Generated by Django 5.2.3 on 2025-08-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('course', 'دورة'), ('installment', 'قسط')], default='course', max_length=20),
        ),
    ]
