# Generated by Django 5.2.3 on 2025-08-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('employee_salary', 'راتب موظف'), ('teacher_salary', 'راتب مدرس'), ('fixed_assets', 'شراء أصول ثابتة'), ('maintenance', 'مصاريف صيانة'), ('printing', 'مصروف طباعة'), ('medical', 'مصروف طبابة'), ('utilities', 'مصروف خدمي'), ('marketing', 'تسويق'), ('copying', 'طباعة'), ('buffet', 'بوفيه'), ('miscellaneous', 'مصاريف متفرقة'), ('government', 'مصاريف حكومية'), ('cleaning', 'تنظيف')], max_length=20, null=True, verbose_name='نوع المصروف'),
        ),
    ]
