# Generated by Django 5.2.3 on 2025-08-23 11:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_status'),
        ('employ', '0004_remove_teacher_contract_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('permission', 'إذن')], default='present', max_length=10, verbose_name='الحالة')),
                ('session_count', models.PositiveIntegerField(default=1, help_text='عدد الجلسات التي قام بها المدرس اليوم', verbose_name='عدد الجلسات')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employ.teacher', verbose_name='المدرس')),
            ],
            options={
                'verbose_name': 'حضور مدرس',
                'verbose_name_plural': 'سجل حضور المدرسين',
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
